ZEPPELIN-5615 Update flapdoodle-mongo to a newer version that supports Linux ARM64
apache/zeppelin pull request #4276
Opened 2021-12-20 08:51 UTC by martin-g

### What is this PR for?

Update the version of Embedded Mongo to a new version that supports Linux ARM64.
Also update the version of Mongo driver

### What type of PR is it?
Improvement

### Todos

No,

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-5615

### How should this be tested?
* The build and tests should pass on Linux ARM64 once it is enabled. See https://github.com/apache/zeppelin/pull/4243

### Screenshots (if appropriate)

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

2021-12-22 15:45 UTC, zjffdu commented
LGTM

2021-12-22 16:52 UTC, Reamer requested changes
Please update the license file.

https://github.com/apache/zeppelin/blob/37cf84a5fef65f40359704e5cb2238264e00a889/zeppelin-distribution/src/bin_license/LICENSE#L227

Everything LGTM

2021-12-22 19:41 UTC, martin-g commented
> Please update the license file.

Done!

2021-12-22 20:15 UTC, Reamer commented
Please take another look at the license line, you missed a part.

2021-12-22 20:37 UTC, martin-g commented
I did!
Improved it!
Thank you!

2021-12-23 13:54 UTC, Reamer approved these changes

2022-01-03 07:02 UTC, Reamer commented
I will merge this PR with the Master branch on Wednesday if no further comments are received.

2022-01-06 07:44 UTC, closed without merging