[NO-ISSUE] Prevent directory escape bypass through repeated URL decoding
apache/zeppelin pull request #4891
Opened 2024-11-03 13:57 UTC by tbonelee

### What is this PR for?
This PR addresses an issue in `NotebookService` where the notebook path validation only performs a single decoding pass.
This allowed a malicious user to bypass validation by double-encoding the `".."` token.
By implementing the repeated decoding, we can prevent this bypass.
Additionally, to prevent excessive decoding attempts, a maximum limit on the number of decoding attempts has been added.

### What type of PR is it?
Hot Fix

### How should this be tested?
* CI

### Questions:
* Does the license files need to update? No
* Is there breaking changes for older versions?
  * There may be minor compatibility issues if a user relies on multiple encoded paths, but this is unlikely in realistic scenarios.
* Does this needs documentation? No

2024-11-03 13:59 UTC, tbonelee commented
cc @jongyoul

2024-11-23 14:27 UTC, tbonelee commented
@pan3793 @Reamer 
When you have a moment, could you check this PR? Appreciate it!

2024-11-24 11:52 UTC, Reamer requested changes
Just a few minor comments. The five attempts seem quite random. But I think it's good that an error message is thrown afterwards.

2024-11-24 11:52 UTC, Reamer commented on zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java
> +      String decoded = URLDecoder.decode(previous, StandardCharsets.UTF_8.toString());
```suggestion
      String decoded = URLDecoder.decode(previous, StandardCharsets.UTF_8);
```
After https://github.com/apache/zeppelin/commit/414f4d1c470b5046628cfc378e6602fb78240e8f, we can now use JDK 11 functions.

2024-11-24 11:52 UTC, Reamer commented on zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java
> +  private String decodeRepeatedly(final String encoded) throws IOException {
This method can be static.
```suggestion
  private static String decodeRepeatedly(final String encoded) throws IOException {
```

2024-11-24 12:17 UTC, tbonelee commented
@Reamer Thank you for the feedback! I've added a commit based on your feedback.

I agree that using five attempts feels somewhat arbitrary. However I couldn't think of a better alternative, so I went with this value.
If you have any other suggestions, I'd love to hear them!

2024-11-24 12:21 UTC, Reamer approved these changes
LGTM, let's wait for CI

2024-11-25 03:41 UTC, pan3793 commented
I read the change and understand what it does, but I don't understand why should this change.
And please create a JIRA ticket for it, if you think this involves CVE which is not suitable to discuss publicly, you can write a detailed message to `private@zeppelin.apache.org`

2024-11-28 08:10 UTC, Reamer commented
I agree with @pan3793 . Please create a Jira ticket and adjust the pull request description accordingly.

2025-05-16 04:42 UTC, tbonelee commented
For context: this PR was based on a security issue I received from @jongyoul, but I didn't have a Jira ticket at the time, which may have caused some confusion.

Apologies for the earlier lack of clarity - I've now created [ZEPPELIN-6190](https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-6190) and linked this PR to it.

2025-05-16 07:25 UTC, jongyoul commented
@tbonelee Thank you for sharing it. 

@pan3793 @Reamer I missed sharing context with others as well. Sorry. This change relates to the security issue, so I thought it would be good to omit creating a ticket. Feel free to reach me if something is not clear. 🙏

2025-06-03 13:13 UTC, merged

2025-06-03 13:15 UTC, Reamer commented
Merged into master and branch-0.12